name: Code checks

on:
  workflow_dispatch:

jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    needs: [linting]
    steps:
    - name: Install pyTest via Requirements.txt
      run: |
        python -m pip install -r requirements.txt
    - name: Run pyTest
      run: |
        pytest tests/


